### ISSUE TITLE
Lib-menu - Compile dependencies

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/lib-menu#14]
A library A should not have an include dependency to a library B.
The library B (latest in case of conflict) will be included when building the application including library A.

TIcket: https://enonic.zendesk.com/agent/tickets/2208

**Comment by GlennRicaud** [comment]
Done but it does not really solves the ticket. There is a bug in the gradle plugin. It is not working the way it was described. A solution meanwhile is to have something like this:
include ('com.enonic.lib:menu:1.2.0') {
        exclude group: 'com.enonic.xp', module: 'lib-content'
    }

**Comment by sigdestad** [comment]
Why is this a problem? Gradle will automatically include the "highest" version of a library used across all libs and apps. Naturally lib-menu needs lib-content and it should be explicitly stated so it is automatically included in an app using lib-menu.

**Comment by GlennRicaud** [comment]
It should yes but with a 'compile' dependency and not an 'include' dependency

**Comment by GlennRicaud** [comment]
And the "Gradle will automatically include the "highest" version of a library used across all libs and apps" from what I just tested it actually does not work

**Comment by sigdestad** [comment]
What is the difference between include and compile?
