### ISSUE TITLE
Register Thymeleaf fragments for the menu code

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/lib-menu#17]
Thymeleaf fragments looks to be global, ship them with this library and one could just "call" on them when needed. That would output the html code required. If custmization is needed the html can be built from scratch and overwrite the lib's code pretty easily.

Bonus: don't depend on one file per level of menu, let thymeleaf recursively generate the menu until done (must be possible).

**Comment by Bellfalasch** [comment]
Works like a charm, will ship in 1.4.0

**Comment by sigdestad** [comment]
NB! Remember to give "unique" names/paths to such files in order to avoid conflict with customer files :-)

**Comment by Bellfalasch** [comment]
Good point! Will make sure it is more in tune with how the library itself does it - `/lib/enonic/menu`for the JS code. Perhaps `/views/fragments/enonic-lib-menu/x`? I'd vote for structuring it into a folder called `fragments` in the `views` folder to keep it organized since view-folder can contain Mustache and XSLT-files.

**Comment by Bellfalasch** [comment]
Updated now, will land in 1.4.0.

```html
<div data-th-replace="/site/views/fragments/enonic-lib-menu/menu :: main-menu"></div>
<div data-th-replace="/site/views/fragments/enonic-lib-menu/breadcrumb :: breadcrumb"></div>
```
