### ISSUE TITLE
Ability to configure the query from the function call

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/lib-menu#23]
Send in properties with the function call specifying additional querying to be done. This might not be so easy to pull off, but that would let you query for additional data before approving items for being in the menu. Like `query: 'displayName != "rubarb" AND data.anotherCheckbox = false'`.

Full example:
```javascript
libs.menu.getMenuTree({
    query: 'displayName != "rubarb" AND data.anotherCheckbox = false',
    levels: 2
});
```

This also requires the function parameter list to be transformed into only one object as param.

**Comment by poi33** [comment]
Should be simple to add the query.

I think most people would think this query is run one time and gets the menu. 
While we currently do this query for each item in the menu.

Add this as an option param to getMenuTree & getSubMenus. 
Should be none breaking.
