### ISSUE TITLE
Ability to configure the returned data from the function call

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/lib-menu#24]
Send in properties with the function call specifying additional data to be returned by the menu function. This might not be so easy to pull off, but that would let you customize your Thymeleaf (view) better, today we're stuck with the data that lib-menu hands you, and if you want more/other data you need to fork the entire project, not only the view-file. Something like `return: ['data.anotherCheckbox','data.myAwesomeField','publish.from']`.

Full example:
```javascript
libs.menu.getMenuTree({
    return: ['data.anotherCheckbox','data.myAwesomeField','publish.from'],
    levels: 2
});
```

This also requires the function parameter list to be transformed into only one object as param.

The normal return of lib-menu's getMenuTree looks like this now:
```
{
        displayName: content.displayName,
        menuName: menuItem.menuName && menuItem.menuName.length ? menuItem.menuName : null,
        path: content._path,
        name: content._name,
        id: content._id,
        hasChildren: subMenus.length > 0,
        inPath: inPath,
        isActive: isActive,
        newWindow: menuItem.newWindow ? menuItem.newWindow : false,
        type: content.type,
        children: subMenus
}
```

Additional (custom) data would append to the end of this return for each content found to be in the menu.

**Comment by poi33** [comment]
Could we add an option to include the full content? 
We allready return so many content fields, might just add an option: 
``
libs.menu.getMenuTree({
    return: 'all',
    levels: 2
});
``
This would not even change much on the speed, so the content is fetched each time anyways.

**Comment by poi33** [comment]
Added this in: bd59bda5560c456123f2b1289de8e767c6cc70e1
