### ISSUE TITLE
Convert getMenuTree to take an object instead of named params

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/lib-menu#25]
It's a breaking-prone design to rely on named parameters for getMenuTree. We need to add more parameters without breaking things for existing users.

We need to convert this to a function that only takes an JS object as single param, and then using sets of properties does things. That way we can easily add functionality over time.

Current way:
```
libs.menu.getMenuTree(2);
```

Improved way:
```
libs.menu.getMenuTree({
    return: ['data.anotherCheckbox','data.myAwesomeField','publish.from'],
    levels: 2
});
```

We could solve this none-breaking by introducing a "proxy"-function with the same name, that just hands over to the new improved function. Meaning `libs.menu.getMenuTree(2);` would still work, but call the new underlying `libs.menu.getMenu({ levels: 2 });` in the back. Function **getMenu()** could then easier be expanded and improved upon, adding more configuration, something we lack today.

Bonus: It would be pretty nice if this new function could combine `getMenuTree` with `getSubMenu` as they use each other anyway and would benefit from having configuration sent in instead (no property with content sent in - use site as default).

**Comment by poi33** [comment]
As of 3.1.0
getMenuTree now has no required params. 
Also has optional parameters:
``
getMenuTree( 2, { 'urlType': 'absolute' } )
``
This should enable us to add additional options.

**Comment by Bellfalasch** [comment]
I like this, very nice work there =) Will be nice for the future of you could send in some custom params and get something extra back in the data response. Today we usually fork lib-menu if we need to customize the response data (like if we need some SEO data, or other custom data).
