### ISSUE TITLE
Inconsistency in where content displayname is stored

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/lib-menu#26]
Menu functions return `.title` and `.displayName` (`.title` is the one that is overwritten from admin). 

Breadcrumb menu handling returns `.text` instead for the title. Use same naming convention!

Optimally, a new title should be added in the return JSON so that the end-user can just use it without custom coding.

**Comment by poi33** [comment]
Is included in pull request #34.

**Comment by poi33** [comment]
v3.1.0 includes the new title propertie. 
Both getBreadcrumbMenu and getMenuTree have a title. 
Will probably remove displayName and menuName in v4.0.0 as this would be breaking.
