### ISSUE TITLE
Return the URL in the menu data

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/lib-menu#27]
Today we fetch the menus, and then in Thymeleaf, or by looping the array again in JS, we resolve the actual URL. This should be done directly and returned with the menu data. This might be breaking as we need to be able to control urlType (like with breadcrumbs).

**Comment by poi33** [comment]
Is included in 94a6d0640ed0a494b177cd9336b7823e85eb4348. 
Should be included in the next release.
