### ISSUE TITLE
Remove tabindex from <span> with active breadcrumb

### ISSUE THREAD

**Issue by tajakobsen** [enonic/lib-menu#38]
The [&lt;span&gt; in breadcrumb.html](https://github.com/enonic/lib-menu/blob/240bc1ef9d0b4fee18106ac08102d73261ffd53b/src/main/resources/site/views/fragments/enonic-lib-menu/breadcrumb.html#L9) that should not have a `[tabindex]`, because it's not an interactive element.

The [article on `tabindex` on MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex#Accessibility_concerns) says the following under "Accessibility concerns":

> Avoid using the tabindex attribute in conjunction with non-interactive content to make something intended to be interactive focusable by keyboard input.

**Comment by poi33** [comment]
I would say the logical tab order would be broken if the "current page" is not tabbable. 
We could simply change the currentPage to an `<a>` element with a href, but then they would link to the current page. 
So the current page is a substitution for a link and that is why i put a tabindex on it. 

Technical [Wcag Focus Order ](https://www.w3.org/TR/WCAG21/#focus-order) ) (Not really breaking it, but wekaen the focus order)

**Comment by tajakobsen** [comment]
I think the intention of *WCAG 2.4.3 Focus Order* is to ensure that you don't use css to reorder elements on your page, so that tab-order is broken.

It does not mean that you should add tabindex to non-interactive elements. That will just make the accessibility worse.

A screen reader (I tested this in NVDA), can just fine [navigate to that element](https://dequeuniversity.com/screenreaders/nvda-keyboard-shortcuts#nvda-the_basics) and read out the `[aria-current]`, without using the tab-key, so there is no reason to make it tabbable.

I don't think an `<a>` with a href is desirable either. But i *do* think an `<a>` *without* a href is the best solution here, because it's not tabbable, but acts as a "placeholder" for a potential link that is shown when this is not the active page anymore.

**Comment by poi33** [comment]
The intention of guideline regarding an example... I'll go with the `<a>` just to get an end to this.

**Comment by poi33** [comment]
bd59bda5560c456123f2b1289de8e767c6cc70e1 shoud change this.
