### ISSUE TITLE
Make `params` for `getMenuTree()` optional

### ISSUE THREAD

**Issue by tajakobsen** [enonic/lib-menu#45]
`getSubMenus()` has `params` as optional, since it provides a [default parameter of `{}`](https://github.com/enonic/lib-menu/blob/a85c1f42997af1d91b3520d509349710f1e47e8e/src/main/resources/lib/menu.js#L142).

I suggest that the same is applied to `getMenuTree()`. Right now I'm forced to call it with an empty object as parameter, like this:

```typescript
getMenuTree(3, {});
```

**Comment by poi33** [comment]
Known issue, we have a fix https://github.com/enonic/lib-menu/tree/empty-param 
Will publish the change probably in 4.0.1

**Comment by poi33** [comment]
Fix released in 4.0.1 😉

**Comment by tajakobsen** [comment]
Sounds good. 

I had a look at the commit https://github.com/enonic/lib-menu/commit/222cb0c42f62bf4cd522b52ea3f54397072460f2, and there might still be a bug there. I commented it on the commit.

**Comment by poi33** [comment]
I prefered explicitly setting the value so fixed it with: 
https://github.com/enonic/lib-menu/blob/771705d6ea2686248292faa490cc9cf0984c6020/src/main/resources/lib/menu.js#L124-L127
