### ISSUE TITLE
Support passing in implicit contentId 

### ISSUE THREAD

**Issue by poi33** [enonic/lib-menu#57]
The functions: 
- getMenuTree
- getBreadcrumbMenu
- getSubMenus 

All use lib portal: getContent and/or getSite
This does not work when used in a service or http controller etc. 
It is possible to support this without adding a breaking change: 
Add content as a new parameter to the functions. 
Then we could get the current site from the pased content. 

Future breaking change. 
getSubMenu with a content parameter. 
getMenuTree & getBreadcrumbMenu optional content param where the site is derived from (like the none breaking chagne above)

**Comment by sigdestad** [comment]
@poi33 - Exactly why do these functions fail in controllers/services?

**Comment by poi33** [comment]
https://github.com/enonic/lib-menu/blob/d8412e38326adc453e2cbf26b030b0cf7fe6a402/src/main/resources/lib/menu.js#L155-L162
Because it uses the current context. As explained above in the description of the issue @sigdestad.

**Comment by sigdestad** [comment]
Rather than implementing this with a new parameter, how about rather moving the logic to discover "nearest content" into lib menu, and then the lib would work just like it has always done?

**Comment by alansemenov** [comment]
I don't understand how lib-menu is supposed to "discover" nearest content. If `portal.getContent()` returns null then we can only use `portal.getSite()` as a fallback. Can you explain?

**Comment by sigdestad** [comment]
The same way that the old context.getContent dit it - basically try accessing each url path above itself until you get a hit (at last the site will be returned).

**Comment by rymsha** [comment]
Discussion  is so similar to #58

**Comment by poi33** [comment]
I would prefer behavior in the lib that is expected. Not search for other content if none can be found. 
Adding content id as a parameter will make it clear where the menu is generated from. No need to read the docs on how nearest content functionality find such a thing.

**Comment by sigdestad** [comment]
And it would break backward compatibility, make it harder to use - with no real gain. Did you ever wonder why things were actually working before?

**Comment by tajakobsen** [comment]
I'm working in a headless environment, and it's problematic for me that `getContent()` is used to calculate  `inPath` and `isActive`.

I would like to be able to pass in the `path` of my current content so it can be used here:
https://github.com/enonic/lib-menu/blob/master/src/main/resources/lib/menu.js#L178

**Comment by sigdestad** [comment]
After discussions we will implement support for passing parameter, and keep backward compatibility by defaulting to current behaviour.
