### ISSUE TITLE
Use request path to find nearest content

### ISSUE THREAD

**Issue by alansemenov** [enonic/lib-menu#58]
If there's no content in the context (`portal.getContent()` returns null), traverse request path to find the nearest content.

**Comment by rymsha** [comment]
Traversing may be not that trivial and even security dangerous (allowing DoS). In XP 7.8 there is a (private) method ContentServiceImpl.doFindNearestByPath that maybe does what you want. It is used to find the nearest site only.

Why would lib-menu need such a functionality (to find nearest content)?

**Comment by alansemenov** [comment]
Because XP 7.8 breaks lib-menu (in [this part](https://github.com/enonic/lib-menu/blob/d8412e38326adc453e2cbf26b030b0cf7fe6a402/src/main/resources/lib/menu.js#L155)) and we need to find a way to solve this without rolling back changes in XP or implementing additional API methods.

**Comment by rymsha** [comment]
It does not explain functionality. 

`getSubMenus()`

```
let currentContent = libs.portal.getContent();

 if (currentContent) {
        return iterateSubMenus(parentContent, levels);
    } else {
        return [];
    }
```

why checking for currentContent, and then not using it at all?

**Comment by alansemenov** [comment]
It _is_ used (search for 'currentContent'). But it's used for decoration purposes (displaying if menu item is current or not etc.), so we can go around it since nearest content will never be the content in context anyway.

**Comment by rymsha** [comment]
Yes, I got confused with functions inside functions. It is in use.

And yes, if it is null it is certainly not current. Traversing path is a waste of resources

**Comment by sigdestad** [comment]
This function should be very fast and can be implemented by getting the site node, then incrementally adding  paths inside site the site to check for content. When result is empty ypu know the path to nearest content. There are rarely more than 3 levels within a site anyway.

**Comment by sigdestad** [comment]
So, No problems related to DoS

**Comment by alansemenov** [comment]
We'll try to solve it without path traversal. As I said, current content from context is used only for decoration purposes.

**Comment by alansemenov** [comment]
Will be solved with https://github.com/enonic/lib-menu/issues/60
