### ISSUE TITLE
Can't build lib-menu version 1.1.1 with the XP 6.1.0 libs.

### ISSUE THREAD

**Issue by Michael-Lazell** [enonic/lib-menu#6]
I seem to get the following gradle build failure unless I set xpVersion to 6.2.0 or higher. 

FAILURE: Build failed with an exception.
- What went wrong:
  Could not copy MANIFEST.MF to '/Users/mla/dev/sourcecode/lib-menu/build/tmp/jar/MANIFEST.MF'.
  > No signature of method: aQute.bnd.osgi.Builder.setProperties() is applicable for argument types: (java.util.LinkedHashMap) values: [[-exportcontents:, Import-Package:_;resolution:=optional, Private-Package:site._;-split-package:=merge-first, ...]]
  Possible solutions: setProperties(java.io.File), setProperties(java.util.Properties), getProperties(), getProperties(), setProperties(java.io.File, java.io.File), addProperties(java.io.File)

**Comment by Bellfalasch** [comment]
Closing this issue as the 6.1.0 release is well over a year old.
