### ISSUE TITLE
Dynamic global.appPath by current content

### ISSUE THREAD

**Issue by rbrastad** [enonic/lib-menu#9]
When having a site with multiple apps. Extradata can be created from any app in the site. 
By setting this appname as is today menuitems will not be shown if they ar ecreated in an other app. So by getting the appname from the current content will  fix the problem.

`function isMenuItem(content) {
    var extraData = content.x;
    if (!extraData) {
        return false;
    }

    // Set appPath to the current objects path. A content can have multiple apps and this need to be dynamic
    globals.appPath = Object.keys(extraData);

    var extraDataModule = extraData[globals.appPath];
    if (!extraDataModule || !extraDataModule['menu-item']) {
        return false;
    }
    var menuItemMetadata = extraDataModule['menu-item'] || {};

    return menuItemMetadata['menuItem'];
}`

**Comment by Bellfalasch** [comment]
Thanks for the heads-up. Just so I understand this:

1. App X adds a content type called Landing Page (which adds the x-data mixin)
2. App Y is the actual website
3. The code for the menu is used on App Y, so it can't find the x-data?

Trying to think about if this way of doing it might have consequences later, or on different setups. If not this sounds like a very good idea and something to implement, thx for the PR.

**Comment by sigdestad** [comment]
Hi @rbrastad. This is not a safe approach as you might get unknown results on x.*.menu-item with varying results. The reason why lib-menu is a lib, is that it is intended to be used inside the App that needs this data. Apps should be 100% independent off each others. In this case you are trying to make a magic dependency which is a no-go.

If you _really_ need to make a dependency like this, it should be hardcoded to lookup for instance x.otherapp.menu-item, not a random scan of data. This would actually be safe as long as you code to think that the property might actually not exist.
